<?php


namespace NewPlayerMC\items\outils;


use pocketmine\block\BlockToolType;
use pocketmine\entity\Entity;
use pocketmine\item\Item;

class Dague extends \pocketmine\item\Tool
{

    public function __construct()
    {
       parent::__construct(445, 0, "Shulker Shell");
    }

    public function getBlockToolType(): int
    {
        return BlockToolType::TYPE_SWORD; // TODO: Change the autogenerated stub
    }

    public function getMaxDurability(): int
    {
        return 10;
    }

    public function onAttackEntity(Entity $victim): bool
    {
        $this->applyDamage(1);
        return true;// TODO: Change the autogenerated stub
    }

}