<?php


namespace NewPlayerMC\items\outils;


use pocketmine\block\Block;
use pocketmine\block\BlockToolType;
use pocketmine\entity\Entity;
use pocketmine\item\Armor;
use pocketmine\item\Bow;
use pocketmine\item\Item;
use pocketmine\item\Pickaxe;
use pocketmine\item\Sword;
use pocketmine\item\TieredTool;
use pocketmine\math\Vector3;
use pocketmine\Player;
use pocketmine\utils\TextFormat;

class EpeeTopaze extends TieredTool
{
    public function __construct(int $meta = 0)
    {
        parent ::__construct(465, $meta, "Epée en Topaze", 5);
    }

    public function getBlockToolType(): int
    {
        return BlockToolType::TYPE_SWORD;
    }

    public function isUnbreakable(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function getAttackPoints(): int
    {
        return 8;
    }

    public function getBlockToolHarvestLevel(): int
    {
        return 1;
    }

    public function getMiningEfficiency(Block $block): float
    {
        return parent ::getMiningEfficiency($block) * 1.5;
    }

    protected function getBaseMiningEfficiency(): float
    {
        return 9;
    }

    public function onDestroyBlock(Block $block): bool
    {
        if ($block -> getHardness() > 0) {
            return $this -> applyDamage(2);
        }
        return false;
    }

    public function onAttackEntity(Entity $victim): bool
    {
        return $this -> applyDamage(1);
    }

    public function getMaxDurability(): int
    {
        return 3660;
    }

}