<?php


namespace NewPlayerMC\items\outils;


use pocketmine\block\Block;
use pocketmine\entity\Entity;
use pocketmine\item\Item;
use pocketmine\item\Shovel;
use pocketmine\item\TieredTool;
use pocketmine\math\Vector3;
use pocketmine\Player;

class PelleSolarite extends Shovel
{
    public function __construct(int $meta = 0)
    {
        parent ::__construct(283, $meta, "Pelle en Solarite", 5);
    }

    public function getBlockToolHarvestLevel(): int
    {
        return 5;
    }

    public function getAttackPoints(): int
    {
        return self ::getBaseDamageFromTier($this -> tier) - 3;
    }

    public function onDestroyBlock(Block $block): bool
    {
        if ($block -> getHardness() > 0) {
            return $this -> applyDamage(1);
        }
        return false;
    }

    public function getMaxDurability(): int
    {
        return 1951;
    }

    public function getMiningEfficiency(Block $block): float
    {
        return parent::getMiningEfficiency($block) * 1.5; // TODO: Change the autogenerated stub
    }

    protected function getBaseMiningEfficiency(): float
    {
        return 11; // TODO: Change the autogenerated stub
    }

    public function onAttackEntity(Entity $victim): bool
    {
        return $this -> applyDamage(2);
    }

    public function isUnbreakable(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}