<?php


namespace NewPlayerMC\items\outils;


use pocketmine\block\BlockToolType;
use pocketmine\item\Armor;
use pocketmine\item\Bow;
use pocketmine\item\Item;
use pocketmine\item\Pickaxe;
use pocketmine\item\Sword;

class Shulk extends \pocketmine\item\Sword
{
    public function __construct()
    {
        parent::__construct(465, 0, "Shulker Shell", 5);
    }

    public function getBlockToolType(): int
    {
        return BlockToolType::TYPE_SWORD; // TODO: Change the autogenerated stub
    }

    public function getAttackPoints(): int
    {
        return parent::getAttackPoints(); // TODO: Change the autogenerated stub
    }

    public static function getType(Item $item, bool $type = true){
        if($item instanceof Sword) return 0x10;
        if($item instanceof Bow) return 0x20;
        if($item instanceof Pickaxe) return 0x400;
        if($type){
            if(in_array($item->getId(), [298, 302, 306, 310, 314])) return 0x1;
            if(in_array($item->getId(), [299, 303, 307, 311, 315])) return 0x2;
            if(in_array($item->getId(), [300, 304, 308, 312, 316])) return 0x4;
            if(in_array($item->getId(), [301, 305, 309, 313, 317])) return 0x8;
        }
        if($item instanceof Armor) return 0x1 | 0x2 | 0x4 | 0x8;
        return null;
    }

}