<?php


namespace NewPlayerMC\items;


use pocketmine\block\Block;
use pocketmine\block\BlockToolType;
use pocketmine\item\Item;
use pocketmine\math\AxisAlignedBB;
use pocketmine\math\Vector3;
use pocketmine\Player;
use pocketmine\tile\Tile;

class ChestMod extends \pocketmine\block\Transparent
{
    protected $id = self::TRAPPED_CHEST;

    public function __construct(int $meta = 0){
        $this->meta = $meta;
    }

    public function getHardness() : float{
        return 3.5;
    }

    public function getBlastResistance(): float
    {
        return 50; // TODO: Change the autogenerated stub
    }

    public function getFuelTime() : int{
        return 300;
    }

}